export default {
    ADD_NOTE:'ADD_NOTE',
    UPDATE_NOT:'UPDATE_NOT',
    DELETE_NOT:'DELETE_NOT',

    SET_INPUT_TITLE:'SET_INPUT_TITLE',
    SET_INPUT_CONTENT:'SET_INPUT_CONTENT',
    SET_INPUT_ID:'SET_INPUT_ID',
    RESET_INPUT:'RESET_INPUT'
}